### ISSUE TITLE
tweet_markets doesn't work / returns tibble length 0

### ISSUE THREAD

**Issue by inh2102** [danielkovtun/rpredictit#1]
<img width="807" alt="Screen Shot 2022-06-26 at 5 25 54 PM" src="https://user-images.githubusercontent.com/61330943/175834372-bd929384-65d4-4b45-b3e5-4162f001f24f.png">

**Comment by danielkovtun** [comment]
@inh2102 unfortunately the tweet markets have long been removed from PredictIt ☹️ 

Thanks for reporting the issue. When I get a chance I will deprecate all tweet-related functions and push a new release to CRAN.
