### ISSUE TITLE
`parse_historical_csv` breaks on 24 hour file

### ISSUE THREAD

**Issue by wmay** [danielkovtun/rpredictit#2]
Running `parse_historical_csv` on a 24 hour csv file leads to an error:

```
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
```

I did some debugging and found that the issue is a wrong time format. It's `%m/%d/%Y %H:%M` but it should be `%m/%d/%Y %I:%M:%S %p`. It's this line here:

https://github.com/danielkovtun/rpredictit/blob/22124820531459e733441d2281dfdc9f8b1f4457/R/market_data.R#L302

**Comment by danielkovtun** [comment]
Thanks for reporting the issue and tracking down the timestamp format. This has been fixed and a new release is available from CRAN (v0.1.0)
